### ISSUE TITLE
JavaScript Error : checkHideMenu

### ISSUE THREAD

**Issue by DasWasseristnass** [NagVis/nagvis#111]
Hi all,

i am using Version 1.9b18. I have following issue:

![image](https://cloud.githubusercontent.com/assets/28728364/26101028/0d65963a-3a30-11e7-98c8-a332e97d5425.png)

I cannot find any solution for it. It looks like a bug.

**Comment by LarsMichelsen** [comment]
Do you use some kind of custom header menu or do you have the header menu disabled somehow? I just pushed a change that tries to fix such a situation

**Comment by DasWasseristnass** [comment]
Hi Lars,

thank you for your fast response. I have tried the commit and get following issue:

![image](https://cloud.githubusercontent.com/assets/28728364/26189904/34128450-3ba7-11e7-8c41-ee16c8daed9d.png)

here is my configuration:

```
; <?php return 1; ?>
[global]
authmodule="CoreAuthModIcingaweb2"
authorisationmodule="CoreAuthorisationModIcingaweb2"
logonmodule="LogonIcingaweb2"

language="de_DE"
[paths]
htmlcgi="/icingaweb2"

[backend_live_1]
backendtype="mklivestatus"
socket="tcp:ICINGA"

[defaults]
urltarget = "_top"
hosturl="[htmlcgi]/monitoring/host/show?host=[host_name]"
hostgroupurl="[htmlcgi]/monitoring/list/hostgroups?hostgroup_name=[hostgroup_name]"
serviceurl="[htmlcgi]/monitoring/service/show?host=[host_name]&service=[service_description]"
servicegroupurl="[htmlcgi]/monitoring/list/servicegroups?servicegroup=[servicegroup_name]"
mapurl="[htmlcgi]/nagvis/show/map?map=[map_name]"
headermenu="0"
stylesheet="icingaweb-nagvis-integration.css"
```

I am using Nagvis with the Icingaweb2 Integration.

https://github.com/Icinga/icingaweb2-module-nagvis

But this issue occurs in the nagvis interface, too.

**Comment by LarsMichelsen** [comment]
How did you apply the change I made? If you only patched the ViewWorldmap.js, you will have to delete the NagVisCompressed.js file. Only in case the later file is not existant the ViewWorldmap.js is loaded.

**Comment by DasWasseristnass** [comment]
Hi Lars,

i used git and the install script, which moves the old folder into an backup directory.

I deleted the NagVisCompressed.js and now it is missing in the js folder. I thought that the file would be regenerated automatically?

Do you need more Information for troubleshooting this problem?

**Comment by wernerfred** [comment]
I think this issue isn't solved yet. Check out what i figured out at #162 
@LarsMichelsen can you please look at it once again?
